#######################################################
#    __  __ _            ____  _     _                #
#   |  \/  (_)_ __   ___/ ___|| |__ (_)_ __   ___     #
#   | |\/| | | '_ \ / _ \___ \| '_ \| | '_ \ / _ \    #
#   | |  | | | | | |  __/___) | | | | | | | |  __/    #
#   |_|  |_|_|_| |_|\___|____/|_| |_|_|_| |_|\___|    #
#               Created by See, Sunix3 and Dom3Zockt! #
#                                                     # 
#######################################################
#                    ChatFormat                       #
#######################################################
#                                                     #
#  Hier kannst du das Format des Chats definieren!    #
#  Folgende Variabeln sind verfügbar:                 #
#                                                     #
#  %playername - [Zeigt den Spielernamen an]          #
#  %Prefix - [Zeigt den Prefix an]                    #
#  %suffix - [Zeigt den Suffix an]                    #
#  %message - [Zeigt die Nachricht des Spielers an]   #
#  &[ChatFarbe] - [Macht etwas Farbig]                #
#                                                     #
MineShine:
  Chat:
    Format: '&7» %prefix &7« %playername: %suffix%message'
#                                                     #
#######################################################
#                      MySQL                          #
#######################################################
#                                                     #
#  Hier legst du alle MySQL-Datenbank-Spezifischen-   #
#  dinge fest! (Ohne MySQL Funktioniert das Plugin    #
#  nicht Richtig!)                                    #
#                                                     #
#                                                     #
MineShine:
  SQL:
    Hostname: 'Host'
    Port: '3306'
    Username: 'User'
    Password: 'Pass'
    Database: 'Database'
#                                                     #
#                                                     #
#######################################################