name: MSS
authors: [See, Dom3Zockt, Sunix3]
version: 0.1
description: The Complete MineShine-Serversystem!
main: me.MineShine.MSS

commands:
  feed:
    description: 'Füllt den Hunger von einem Spieler auf.'
    aliases: [eat]
  stack:
    description: 'Setzt alle Items im Inventar zu 64er Itemstacks.'
  enchant:
    description: 'Verzaubert das Item, dass der Spieler in der Hand hat.'
  exp:
    description: 'Setzt die EXP-Leiste eines Spielers'
    aliases: [xp]
  fly:
    description: 'Erlaubt Spielern zu Fliegen.'