name: MSS
authors: [See, Dom3Zockt, Sunix3]
version: 0.1
description: The Complete MineShine-Serversystem!
main: me.MineShine.MSS

commands:
  feed:
    description: 'Füllt den Hunger von einem Spieler auf.'
    aliases: [eat]
  stack:
    description: 'Setzt alle Items im Inventar zu 64er Itemstacks.'
  enchant:
    description: 'Verzaubert das Item, dass der Spieler in der Hand hat.'
  exp:
    description: 'Setzt die EXP-Leiste eines Spielers'
    aliases: [xp]
  fly:
    description: 'Erlaubt Spielern zu Fliegen.'
  clearlag:
    description: 'Löscht alle Entities in einer Welt.'
    aliases: [cl]
  msg:
    description: 'Sends a Message to a Player'
    aliases: [t, m, tell, w, whisper]
  reply:
    description: 'Sends a Message to a Player, who send a Message to the Sender before.'
    aliases: [r, answer]
  socialspy:
    description: 'Sends a Message with the String of every MSG commands to all Players with a Certain Permission.'
  gamemode:
    description: 'Sets the Gamemode of a Player.'
    aliases: [gm]
  enderchest:
    description: 'Opens the Enderchest of a Player.'
    aliases: [ec]
  ping:
    description: 'Returns IP, Playername and Ping of a Playre.'
    aliases: [pong]
  repair:
    description: 'Sets the Durability of all Items in a Players inventory to 0'
    aliases: [fix]
  workbench:
    description: 'Opens an Inventory with Type Workbench.'
    aliases: [wb]
  me:
    description: 'Sends a Message.'
  more:
    description: 'Sets the Amount of the Item in the Players Hand to 64.'
  god:
    description: 'Makes a Player invincible.'